version: '3.6'
services:
  storeDbM:
    container_name: storeDbM
    image: api-store-bd-m:1.0
    volumes:
      - /volume/shCript:/shScript
    environment:
      Lang: en_us.utf-8
      seconds: 86400
    command: sh -c " java -jar -Dfile.encoding=UTF8 jar/filldataBase.jar $${seconds}"
    